language: python
python: 3.5

jobs:
  include:
    - install: pip install tox coveralls
      script: tox
      after_success: coveralls
    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: fetzerch
        password:
          secure: fVTcN76RpPTCIHyUd4Xg2COpVa/3CuFPRi8DBHqdGWjTuqU/UhXFORYL56eQUnAuhdjt8kNV757tmB6cf1uxlH0v4WAPlwiij3Zw9Wr+QBw+D71jfDLB+b/zGPlwyCuvLyZPP202UknUXvKGw2uHbOiTcW85v4ITZgBQ2/yDVUSfqJpMHU9LFGwePbaJdxbBzifSx1jdShtrc8POtm8ddi1N1h3zCt2osfTxmVGH0eQOAunCGwWT2rTawLPQnSqCg8yVLBo8iCYzkghZcByn+DGLU36s4fVFKG0xGVTUOdyT7VciIIsyjwVNGyG9ap5LxGVyQnV4jrSNrSYvnNSqKwQceRq/l/RyFC4tEaOPzEOA+GiCBy+Pyh7ZmVRuymDeVLWWIdN3UBoqM7GRNhuAxUhoNkfP6IlwSfRpbNqVbeObOKLU4Guf4VMk/YGjSLIssl4KIZ8sdnn8/MFln6p0xgjPvFF82Zms8XYjEMCzM/kXSbeHa+Cyv6Xbi9+yHauU69uclTQpMo1VSINJn2hwQYauJw0YXDDjVl1Tb2VHNATLgI37GZINm9dTHju/vMdXzQAXfOSOww5Iqmah+HMpCS7dJNp62RVGjHR2a+7j08LntEUB2HmxYCvD7YEwEIbOhv2/S/v207WECvPYyZuB9V7Ca35Ygf03LAio/reESVo=
        on:
          tags: true
